"""M6 gate — THE FULL GOLDEN RUN (SPEC §9.2 + §10 M6; ADAPTATION D3/D5).

The 6-entity fixture (LE-US parent / LE-NL hub / DE / FR / JP / LE-UK
reciprocal partner; POOL-IT-INFRA ⇄ POOL-FIN-SSC reciprocal pair, SCM 0%
US-leg, POOL-MGMT 30% stewardship carve-out + multi-factor key, 12 Budget
months + Actual year + true-up with +8%/+15% divergences) lives in
``golden/fixture.json`` with its expected outputs in ``golden/expected.json``
— both generated by ``golden/build_fixture.py``, the COMMITTED, clearly
labelled INDEPENDENT hand-computation (it never imports the engine).

Assertions per SPEC §9.2, in order:

- every charge amount TO THE CENT, all 12 months, Budget AND Actual —
  against expected.json AND hard-coded literals (so the gate is not
  self-referential);
- every recon row Balanced with an EXACTLY zero residual;
- the reciprocal solution matches the hand-solved linear system (1e-10);
- the explicit cascade: IT's SCM charge to LE-US becomes a received cost
  line in POOL-MGMT (V-C3 lineage by construction);
- true-up deltas to the cent, parents = the latest booked Budget charges;
- exactly the expected V-rules fire: V-X3 ONCE (POOL-IT-INFRA), V-C2 NEVER
  (default "single" config), nothing else all year;
- a re-run of identical inputs reproduces identical input AND output hashes
  (V-X4 green);
- the committed fixture/expected files match the builder (drift check).

NO float arithmetic on amounts anywhere in this file (ENGINE-CLAUDE.md).

Run from backend/:
    ../.venv/bin/python -m pytest tests/allocation/test_m6_golden_run.py
"""

from __future__ import annotations

import json
from decimal import Decimal
from pathlib import Path

import pytest

import services.allocation_runner as runner
import state.allocation_store as store
import state.engine as engine
from allocation.algorithms.cascade import cascade_allocate
from allocation.stages import (
    stage1_capture_and_classify,
    stage2_pool,
    stage3_benefit_gate,
)
from tests.allocation.golden import build_fixture as builder

GOLD = Path(__file__).resolve().parent / "golden"
FIXTURE = json.loads((GOLD / "fixture.json").read_text(encoding="utf-8"))
EXPECTED = json.loads((GOLD / "expected.json").read_text(encoding="utf-8"))
CONFIG = EXPECTED["config"]
MONTHS = [f"2026-{m:02d}" for m in range(1, 13)]
ZERO = Decimal("0")
TOL = Decimal("1E-10")

POOL_MGMT, POOL_IT, POOL_FIN = "POOL-MGMT", "POOL-IT-INFRA", "POOL-FIN-SSC"


def _engine_id(charge_id: str) -> str:
    return charge_id.split(":", 1)[1] if ":" in charge_id else charge_id


@pytest.fixture(scope="module")
def golden(tmp_path_factory):
    """One isolated DB for the whole golden gate: 12 Budget runs + 12 Actual
    runs + the true-up + the V-X4 re-run, executed once."""
    engine.configure(tmp_path_factory.mktemp("golden") / "state.db")
    engine.init_db()
    runs: dict[str, dict[str, dict]] = {"budget": {}, "actual": {}}
    for run_type in ("budget", "actual"):
        for period in MONTHS:
            runs[run_type][period] = runner.run_allocation(
                period=period, run_type=run_type, actor="golden",
                config=CONFIG, dataset=FIXTURE)
    trueup = runner.run_allocation(period="2026", run_type="trueup",
                                   actor="golden", config=CONFIG,
                                   dataset=FIXTURE)
    rerun = runner.run_allocation(period="2026-03", run_type="budget",
                                  actor="golden", config=CONFIG,
                                  dataset=FIXTURE)
    yield {"runs": runs, "trueup": trueup, "rerun": rerun}
    engine.close()


# ------------------------------------------------------------ commit checks --


def test_committed_fixture_and_expected_match_the_builder():
    """Drift check: the committed JSON is exactly what the independent
    builder derives (re-run golden/build_fixture.py after any change)."""
    assert builder.build_dataset() == FIXTURE
    actual = {p: builder.run_period(p, "actual") for p in MONTHS}
    budget = {p: builder.run_period(p, "budget") for p in MONTHS}
    assert {p: budget[p]["ledger"] for p in MONTHS} == EXPECTED["budget"]
    assert {p: actual[p]["ledger"] for p in MONTHS} == EXPECTED["actual"]
    assert builder.build_trueup(actual, budget) == EXPECTED["trueup"]


# ------------------------------------------------- charges, to the cent ------


@pytest.mark.parametrize("run_type", ["budget", "actual"])
def test_every_charge_amount_to_the_cent_all_12_months(golden, run_type):
    """SPEC §9.2 — every charge amount, every month, to the cent, against
    the independent computation."""
    for period in MONTHS:
        res = golden["runs"][run_type][period]
        assert res["status"] == "succeeded", (period, run_type)
        rows = {_engine_id(r["charge_id"]): r
                for r in store.list_charges(run_id=res["run_id"])}
        expected = EXPECTED[run_type][period]
        assert set(rows) == set(expected), (period, run_type)
        for eid, exp in expected.items():
            row = rows[eid]
            for field, value in exp.items():
                if field == "charge_id":
                    continue
                assert row[field] == value, (period, run_type, eid, field)


def test_hard_coded_literals_2026_01_actual(golden):
    """Key figures hard-coded from the hand computation (NOT read from
    expected.json) — the gate is not self-referential: the SCM 0% US leg,
    an LVAIGS EUR leg, the zero-decimal JPY leg and a cascaded MGMT leg."""
    res = golden["runs"]["actual"]["2026-01"]
    rows = {_engine_id(r["charge_id"]): r
            for r in store.list_charges(run_id=res["run_id"])}
    assert len(rows) == 10  # FIN: DE/FR/JP · IT: DE/FR/JP/US · MGMT: DE/FR/JP

    us = rows["CHG-2026-01-POOL-IT-INFRA-LE-US"]   # SCM (0%) US leg
    assert us["cost_recovered_amount"] == "143849.40"
    assert us["markup_amount"] == "0.00"
    assert us["gross_charge_amount"] == "143849.40"
    assert us["charge_currency"] == "USD"
    assert us["markup_pct_applied"] == "0"

    de = rows["CHG-2026-01-POOL-IT-INFRA-LE-DE"]   # LVAIGS 5%, EUR @ 0.92
    assert de["cost_recovered_amount"] == "108279.37"
    assert de["markup_amount"] == "4648.59"
    assert de["gross_charge_amount"] == "112927.96"
    assert de["charge_currency"] == "EUR"
    assert de["fx_rate"] == "0.92"

    jp = rows["CHG-2026-01-POOL-FIN-SSC-LE-JP"]    # zero-decimal JPY @ 150
    assert jp["cost_recovered_amount"] == "3993291"
    assert jp["markup_amount"] == "150626"
    assert jp["gross_charge_amount"] == "4143917"
    assert jp["charge_currency"] == "JPY"

    mg = rows["CHG-2026-01-POOL-MGMT-LE-DE"]       # own cost marked up; the
    assert mg["cost_recovered_amount"] == "87381.41"   # received IT component
    assert mg["markup_amount"] == "2005.83"            # passes through at 0%
    assert mg["gross_charge_amount"] == "89387.24"
    # markup < 5% of cost: the received component is NOT re-margined
    assert Decimal(mg["markup_amount"]) \
        < Decimal(mg["cost_recovered_amount"]) * Decimal("0.05")


# --------------------------------------------------------------- recon -------


def test_every_recon_row_balanced_with_exactly_zero_residual(golden):
    """SPEC §9.2 — every recon row Balanced, residual EXACTLY zero (V-X1
    hard zero), figures matching the independent computation."""
    for run_type in ("budget", "actual"):
        for period in MONTHS:
            res = golden["runs"][run_type][period]
            recon = store.list_recon(run_id=res["run_id"])
            assert len(recon) == 3
            expected = EXPECTED[f"recon_{run_type}"][period]
            for row in recon:
                exp = expected[row["pool_id"]]
                assert row["recon_status"] == "Balanced"
                assert Decimal(row["unallocated_residual"]) == ZERO
                for field in ("total_pooled_cost", "total_exclusions",
                              "total_cost_recovered", "total_markup",
                              "total_charged_out"):
                    assert Decimal(row[field]) == Decimal(exp[field]), \
                        (run_type, period, row["pool_id"], field)
    for row in store.list_recon(run_id=golden["trueup"]["run_id"]):
        assert row["recon_status"] == "Balanced"
        assert Decimal(row["unallocated_residual"]) == ZERO


def test_mgmt_stewardship_carve_out_is_30_pct_of_own_cost(golden):
    """The 30% carve-out applies to POOL-MGMT's OWN cost only — the injected
    received charge is never re-gated (pooled − exclusions − base ties)."""
    res = golden["runs"]["actual"]["2026-01"]
    row = next(r for r in store.list_recon(run_id=res["run_id"])
               if r["pool_id"] == POOL_MGMT)
    own = Decimal("174420")            # (108000+1080) + (64800+540), m=1 ×1.08
    injected = Decimal("143849.40")    # IT's gross SCM charge to LE-US
    assert Decimal(row["total_exclusions"]) == own * Decimal("0.30")
    assert Decimal(row["total_pooled_cost"]) == own + injected


# ----------------------------------------------- reciprocal & cascade --------


def _stage3_pools(period: str, source: str) -> tuple[list[dict], dict]:
    cfg = {**CONFIG, "period": period}
    ref = {k: FIXTURE[k] for k in ("entities", "cc_mapping", "pools",
                                   "markup_policies", "exclusions",
                                   "key_defs", "participation")}
    ref["key_values"] = FIXTURE["key_values"][source]
    lines = [r for r in FIXTURE["cost_lines"][source]
             if r["fiscal_period"] == period]
    s1 = stage1_capture_and_classify({"cost_lines": lines}, ref, cfg)
    s2 = stage2_pool({"classified_lines": s1["outputs"]["classified_lines"]},
                     ref, cfg)
    s3 = stage3_benefit_gate({"pools": s2["outputs"]["pools"]}, ref, cfg)
    return s3["outputs"]["pools"], {**ref}


def test_reciprocal_solution_matches_the_hand_solved_linear_system():
    """SPEC §9.2 — the engine's solved S equals the hand-solved 2×2 system
    (within the solver's 1e-10 tolerance) and conservation holds: the SCC
    charges out exactly its combined cost."""
    pools, ref = _stage3_pools("2026-01", "actual")
    res = cascade_allocate({"pools": pools}, ref, {**CONFIG, "period": "2026-01"})
    assert res["exceptions"] == []
    by_id = {p["pool_id"]: p for p in res["outputs"]["pools"]}
    # hand-solved literals (golden/build_fixture.py — independent derivation)
    assert abs(by_id[POOL_IT]["solved_cost"]
               - Decimal("470779.8561151079136690647482")) <= TOL
    assert abs(by_id[POOL_FIN]["solved_cost"]
               - Decimal("159731.6546762589928057553957")) <= TOL
    assert by_id[POOL_IT]["reciprocal_scc"] == [POOL_FIN, POOL_IT]
    # expected.json carries the solved system for every month
    for pool in (POOL_IT, POOL_FIN):
        assert abs(by_id[pool]["solved_cost"]
                   - Decimal(EXPECTED["solved"]["2026-01"][pool])) <= TOL
    # conservation (SPEC §9.3): total in == total charged out across the SCC
    scc_out = sum((a["allocated_cost"] for a in res["outputs"]["allocations"]
                   if a["pool_id"] in (POOL_IT, POOL_FIN)), ZERO)
    assert scc_out == (by_id[POOL_IT]["chargeable_base"]
                       + by_id[POOL_FIN]["chargeable_base"])


def test_cascade_received_cost_line_joins_pool_mgmt(golden):
    """SPEC §5.2 — the IT SCM charge to LE-US becomes a received cost line
    in POOL-MGMT (lineage to the originating charge, V-C3 by construction);
    visible in the persisted lineage artifact."""
    res = golden["runs"]["actual"]["2026-01"]
    lineage = json.loads(store.get_artifact(
        res["run_id"], "lineage.json")["content"])
    mgmt_charges = {cid: e for cid, e in lineage["charges"].items()
                    if e["pool_id"] == POOL_MGMT}
    received_id = "CL-RCV-CHG-2026-01-POOL-IT-INFRA-LE-US"
    assert all(received_id in e["line_ids"] for e in mgmt_charges.values())
    line = lineage["lines"][received_id]
    assert line["cost_nature"] == "Intercompany charge received"
    assert line["amount_local"] == "143849.40"   # the upstream GROSS
    assert line["source_document_ref"] == "CHG-2026-01-POOL-IT-INFRA-LE-US"
    assert line["provider_entity_id"] == "LE-US"


# --------------------------------------------------------------- true-up -----


def test_trueup_deltas_to_the_cent_with_booked_parents(golden):
    """SPEC §5.4 / §9.2 — one True-up row per (pool, provider, recipient,
    year), amounts to the cent, FX at the year-end closing rate, parent =
    the latest booked Budget charge."""
    res = golden["trueup"]
    assert res["status"] == "succeeded"
    rows = {_engine_id(r["charge_id"]): r
            for r in store.list_charges(run_id=res["run_id"])}
    expected = EXPECTED["trueup"]["rows"]
    assert set(rows) == set(expected)
    dec_12_budget_run = golden["runs"]["budget"]["2026-12"]["run_id"]
    for eid, exp in expected.items():
        row = rows[eid]
        for field, value in exp.items():
            if field in ("charge_id", "delta_gross_provider_ccy"):
                continue
            if field == "true_up_parent_charge_id":
                # persisted parents are run-namespaced ids of the latest
                # booked Budget run for 2026-12
                assert row[field] == f"{dec_12_budget_run}:{value}", eid
                assert store.get_charge(row[field]) is not None
                continue
            assert row[field] == value, (eid, field)
        assert row["budget_or_actual"] == "True-up"

    # hard-coded literals (independent hand computation)
    assert rows["CHG-2026-POOL-IT-INFRA-LE-US-TRUEUP"][
        "gross_charge_amount"] == "204979.86"            # USD identity
    assert rows["CHG-2026-POOL-MGMT-LE-DE-TRUEUP"][
        "gross_charge_amount"] == "110184.89"            # EUR @ 0.95 year-end
    assert rows["CHG-2026-POOL-MGMT-LE-DE-TRUEUP"]["fx_rate"] == "0.95"
    assert rows["CHG-2026-POOL-MGMT-LE-DE-TRUEUP"]["fx_rate_type"] == "Spot"
    assert rows["CHG-2026-POOL-FIN-SSC-LE-JP-TRUEUP"][
        "gross_charge_amount"] == "1444177"              # JPY @ 155, no decimals
    # FIN's markup base (own cost) never diverged — pure cost delta
    assert rows["CHG-2026-POOL-FIN-SSC-LE-DE-TRUEUP"]["markup_amount"] == "0.00"


def test_trueup_recon_records_the_deltas(golden):
    """SPEC §5.4 — true_up_delta on 11_Recon, per pool, in the provider's
    booking currency (hard-coded from the hand computation)."""
    recon = {r["pool_id"]: r
             for r in store.list_recon(run_id=golden["trueup"]["run_id"])}
    assert Decimal(recon[POOL_IT]["true_up_delta"]) == Decimal("634725.82")
    assert Decimal(recon[POOL_MGMT]["true_up_delta"]) == Decimal("324755.46")
    assert Decimal(recon[POOL_FIN]["true_up_delta"]) == Decimal("32610.42")
    for pool, kpi in EXPECTED["trueup"]["by_pool"].items():
        assert Decimal(recon[pool]["true_up_delta"]) == Decimal(kpi["delta_gross"])


# ------------------------------------------------------ V-rules, exactly -----


def test_exactly_the_expected_v_rules_fire(golden):
    """SPEC §9.2 — V-X3 exactly ONCE (POOL-IT-INFRA: |delta|/actual ≈ 11.6%
    > 10%; POOL-MGMT 9.6% and POOL-FIN-SSC 2.7% stay under); V-C2 NEVER
    (default "single" margin policy); nothing else, all year."""
    for run_type in ("budget", "actual"):
        for period in MONTHS:
            report = golden["runs"][run_type][period]["exception_report"]
            assert report["exceptions"] == [], (run_type, period)
    report = golden["trueup"]["exception_report"]
    assert [(e["rule_id"], e["pool_id"], e["severity"])
            for e in report["exceptions"]] \
        == [("V-X3", POOL_IT, "WARN")]
    assert report["counts"] == {"BLOCK": 0, "WARN": 1}
    # the KPI ratios behind the single firing (independent derivation)
    by_pool = EXPECTED["trueup"]["by_pool"]
    assert Decimal(by_pool[POOL_IT]["ratio"]) > Decimal("0.10")
    assert Decimal(by_pool[POOL_MGMT]["ratio"]) < Decimal("0.10")
    assert Decimal(by_pool[POOL_FIN]["ratio"]) < Decimal("0.10")


# ------------------------------------------------------- hash reproducibility


def test_rerun_reproduces_identical_hashes_v_x4(golden):
    """SPEC §9.2 / V-X4 — re-running 2026-03 Budget on identical inputs
    reproduces the identical input snapshot hash AND output hash; the run
    succeeds (no V-X4) and the ledger stays append-only (a second, fully
    identical set of rows under the new run_id)."""
    first = golden["runs"]["budget"]["2026-03"]
    rerun = golden["rerun"]
    assert rerun["status"] == "succeeded"
    assert rerun["exception_report"]["exceptions"] == []
    assert rerun["input_snapshot_hash"] == first["input_snapshot_hash"]
    h1 = store.get_artifact(first["run_id"], "output.sha256")["content"]
    h2 = store.get_artifact(rerun["run_id"], "output.sha256")["content"]
    assert h1 == h2
    rows1 = {_engine_id(r["charge_id"]): {k: v for k, v in r.items()
                                          if k not in ("charge_id", "run_id",
                                                       "documentation_ref")}
             for r in store.list_charges(run_id=first["run_id"])}
    rows2 = {_engine_id(r["charge_id"]): {k: v for k, v in r.items()
                                          if k not in ("charge_id", "run_id",
                                                       "documentation_ref")}
             for r in store.list_charges(run_id=rerun["run_id"])}
    assert rows1 == rows2


def test_doc_pack_emitted_per_pool_with_tie_out(golden):
    """SPEC §8.3 — one Markdown document per pool per period, recon tie-out
    included (the generator's own unit tests live in
    test_m6_stage7_trueup_docpack.py)."""
    res = golden["runs"]["actual"]["2026-01"]
    docs = [a["name"] for a in store.list_artifacts(res["run_id"])
            if a["name"].startswith("docs/")]
    assert docs == [f"docs/{POOL_FIN}.md", f"docs/{POOL_IT}.md",
                    f"docs/{POOL_MGMT}.md"]
    md = store.get_artifact(res["run_id"], f"docs/{POOL_MGMT}.md")["content"]
    assert "## 8. Reconciliation tie-out" in md
    assert "Balanced" in md
    assert "OECD TPG" in md            # the stewardship rationale
    assert "Multi-factor" in md        # the multi-factor key
